// formulario-react/src/components/usuarios/UsuarioDetail.jsx
import { useState, useEffect, useCallback } from 'react';
import { getUsuariobyId } from '../../services/usuariosService';
import '../../styles/usuarios.css';
import '../../styles/dashboard.css';

const UsuarioDetail = ({ usuarioId, onClose }) => {
  const [usuario, setUsuario] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState('');

  // Obtener detalles del usuario
  const fetchUsuarioDetail = useCallback(async () => {
    setIsLoading(true);
    setErrorMessage('');
    try {
      const response = await getUsuariobyId(usuarioId);
      if (response.success) {
        setUsuario(response.data);
      }
    } catch (error) {
      console.error('Error al cargar detalles del usuario:', error);
      setErrorMessage('Error al cargar detalles del usuario. Intenta nuevamente.');
    } finally {
      setIsLoading(false);
    }
  }, [usuarioId]);

  // Cargar detalles del usuario al montar
  useEffect(() => {
    fetchUsuarioDetail();
  }, [fetchUsuarioDetail]);

  // Formatear fecha
  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('es-EC', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  // Obtener iniciales para el avatar
  const getInitials = (nombres, apellidos) => {
    const firstInitial = nombres?.charAt(0) || '';
    const lastInitial = apellidos?.charAt(0) || '';
    return (firstInitial + lastInitial).toUpperCase();
  };

  // Calcular edad
  const calculateAge = (birthDate) => {
    const today = new Date();
    const birth = new Date(birthDate);
    let age = today.getFullYear() - birth.getFullYear();
    const monthDiff = today.getMonth() - birth.getMonth();

    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birth.getDate())) {
      age--;
    }

    return age;
  };

  if (isLoading) {
    return (
      <div className="modal-overlay" onClick={onClose}>
        <div className="modal-content" onClick={(e) => e.stopPropagation()}>
          <div className="modal-body">
            <div className="usuarios-loading">
              <div className="spinner"></div>
              <p className="usuarios-loading-text">Cargando detalles...</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (errorMessage || !usuario) {
    return (
      <div className="modal-overlay" onClick={onClose}>
        <div className="modal-content" onClick={(e) => e.stopPropagation()}>
          <div className="modal-header">
            <h2 className="modal-title">👤 Detalles del Usuario</h2>
            <button className="modal-close" onClick={onClose}>
              ✕
            </button>
          </div>
          <div className="modal-body">
            <div className="alert alert-error">
              {errorMessage || 'Usuario no encontrado'}
            </div>
          </div>
          <div className="modal-footer">
            <button className="btn btn-secondary" onClick={onClose}>
              Cerrar
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="modal-header">
          <h2 className="modal-title">👤 Detalles del Usuario</h2>
          <button className="modal-close" onClick={onClose}>
            ✕
          </button>
        </div>

        {/* Body */}
        <div className="modal-body">
          {/* Avatar y nombre */}
          <div className="usuario-detail-header">
            <div className="usuario-avatar-large">
              {getInitials(usuario.nombres, usuario.apellidos)}
            </div>
            <div className="usuario-detail-info">
              <h3 className="usuario-detail-name">
                {usuario.nombres} {usuario.apellidos}
              </h3>
              <p className="usuario-detail-email">{usuario.email}</p>
            </div>
          </div>

          {/* Información detallada */}
          <div className="usuario-detail-grid">
            <div className="usuario-detail-item">
              <span className="usuario-detail-label">DNI / Cédula</span>
              <span className="usuario-detail-value">{usuario.dni}</span>
            </div>

            <div className="usuario-detail-item">
              <span className="usuario-detail-label">Fecha de Nacimiento</span>
              <span className="usuario-detail-value">
                {formatDate(usuario.fecha_nacimiento)} ({calculateAge(usuario.fecha_nacimiento)} años)
              </span>
            </div>

            <div className="usuario-detail-item">
              <span className="usuario-detail-label">Género</span>
              <span className="usuario-detail-value">
                <span className={`usuario-badge ${usuario.genero}`}>
                  {usuario.genero}
                </span>
              </span>
            </div>

            <div className="usuario-detail-item">
              <span className="usuario-detail-label">Ciudad</span>
              <span className="usuario-detail-value">{usuario.ciudad}</span>
            </div>

            <div className="usuario-detail-item">
              <span className="usuario-detail-label">Email</span>
              <span className="usuario-detail-value">{usuario.email}</span>
            </div>

            <div className="usuario-detail-item">
              <span className="usuario-detail-label">ID de Usuario</span>
              <span className="usuario-detail-value">{usuario.id}</span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={onClose}>
            Cerrar
          </button>
        </div>
      </div>
    </div>
  );
};

export default UsuarioDetail;

// formulario-vue/src/components/usuarios/UsuarioDetail.vue
<template>
  <div class="modal-overlay" @click="$emit('close')">
    <div class="detail-modal" @click.stop>
      <!-- Header -->
      <div class="modal-header">
        <h2 class="modal-title">
          <span>👤</span>
          Detalle de Usuario
        </h2>
        <button class="modal-close-btn" @click="$emit('close')">✕</button>
      </div>

      <!-- Loading -->
      <div v-if="isLoading" class="modal-body">
        <div class="loading-state">
          <div class="spinner"></div>
          <p class="loading-text">Cargando información...</p>
        </div>
      </div>

      <!-- Error -->
      <div v-else-if="error" class="modal-body">
        <div class="alert alert-error">
          ⚠️ {{ error }}
        </div>
      </div>

      <!-- Content -->
      <div v-else-if="usuario" class="modal-body">
        <!-- Avatar y nombre -->
        <div class="detail-header">
          <div class="detail-avatar">
            {{ getInitials(usuario.nombres, usuario.apellidos) }}
          </div>
          <div class="detail-name">
            <h3>{{ usuario.nombres }} {{ usuario.apellidos }}</h3>
            <p>{{ usuario.email }}</p>
          </div>
        </div>

        <!-- Información detallada -->
        <div class="detail-info-grid">
          <div class="detail-info-card">
            <div class="detail-info-icon">🆔</div>
            <div class="detail-info-content">
              <span class="detail-info-label">DNI / Cédula</span>
              <span class="detail-info-value">{{ usuario.dni }}</span>
            </div>
          </div>

          <div class="detail-info-card">
            <div class="detail-info-icon">📅</div>
            <div class="detail-info-content">
              <span class="detail-info-label">Fecha de Nacimiento</span>
              <span class="detail-info-value">{{ formatFullDate(usuario.fecha_nacimiento) }}</span>
              <span class="detail-info-extra">{{ calculateAge(usuario.fecha_nacimiento) }} años</span>
            </div>
          </div>

          <div class="detail-info-card">
            <div class="detail-info-icon">{{ usuario.genero === 'masculino' ? '👨' : '👩' }}</div>
            <div class="detail-info-content">
              <span class="detail-info-label">Género</span>
              <span class="detail-info-value">{{ usuario.genero }}</span>
            </div>
          </div>

          <div class="detail-info-card">
            <div class="detail-info-icon">📍</div>
            <div class="detail-info-content">
              <span class="detail-info-label">Ciudad</span>
              <span class="detail-info-value">{{ usuario.ciudad }}</span>
            </div>
          </div>

          <div class="detail-info-card">
            <div class="detail-info-icon">📧</div>
            <div class="detail-info-content">
              <span class="detail-info-label">Email</span>
              <span class="detail-info-value">{{ usuario.email }}</span>
            </div>
          </div>

          <div class="detail-info-card">
            <div class="detail-info-icon">🕒</div>
            <div class="detail-info-content">
              <span class="detail-info-label">Registro</span>
              <span class="detail-info-value">{{ formatFullDate(usuario.created_at) }}</span>
            </div>
          </div>

          <div v-if="usuario.updated_at" class="detail-info-card">
            <div class="detail-info-icon">🔄</div>
            <div class="detail-info-content">
              <span class="detail-info-label">Última Actualización</span>
              <span class="detail-info-value">{{ formatFullDate(usuario.updated_at) }}</span>
            </div>
          </div>

          <div class="detail-info-card">
            <div class="detail-info-icon">#️⃣</div>
            <div class="detail-info-content">
              <span class="detail-info-label">ID del Sistema</span>
              <span class="detail-info-value">{{ usuario.id }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="modal-footer">
        <button class="btn btn-outline" @click="$emit('close')">
          Cerrar
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, onMounted } from 'vue';
import { getUsuarioById } from '../../services/usuariosService';

export default {
  name: 'UsuarioDetail',
  props: {
    usuarioId: {
      type: Number,
      required: true
    }
  },
  emits: ['close'],
  setup(props) {
    const usuario = ref(null);
    const isLoading = ref(true);
    const error = ref('');

    const fetchUsuario = async () => {
      isLoading.value = true;
      error.value = '';
      
      try {
        const response = await getUsuarioById(props.usuarioId);
        if (response.success) {
          usuario.value = response.data;
        }
      } catch (err) {
        error.value = err.message || 'Error al cargar el usuario';
      } finally {
        isLoading.value = false;
      }
    };

    const getInitials = (nombres, apellidos) => {
      return (nombres.charAt(0) + apellidos.charAt(0)).toUpperCase();
    };

    const formatFullDate = (dateString) => {
      const date = new Date(dateString);
      return date.toLocaleDateString('es-EC', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });
    };

    const calculateAge = (birthDate) => {
      const today = new Date();
      const birth = new Date(birthDate);
      let age = today.getFullYear() - birth.getFullYear();
      const monthDiff = today.getMonth() - birth.getMonth();
      
      if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birth.getDate())) {
        age--;
      }
      
      return age;
    };

    onMounted(() => {
      fetchUsuario();
    });

    return {
      usuario,
      isLoading,
      error,
      getInitials,
      formatFullDate,
      calculateAge
    };
  }
};
</script>

<style scoped>
.detail-modal {
  position: fixed;
  right: 0;
  top: 0;
  bottom: 0;
  width: 100%;
  max-width: 700px;
  background-color: var(--white);
  box-shadow: var(--shadow-xl);
  animation: slideInRight 0.3s ease-out;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.detail-header {
  display: flex;
  align-items: center;
  gap: var(--spacing-lg);
  padding: var(--spacing-xl);
  background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
  color: var(--white);
  border-radius: var(--radius-lg);
  margin-bottom: var(--spacing-xl);
}

.detail-avatar {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  background: var(--white);
  color: var(--primary-color);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 2rem;
  font-weight: 700;
  box-shadow: var(--shadow-lg);
  flex-shrink: 0;
}

.detail-name h3 {
  font-size: 1.5rem;
  font-weight: 700;
  margin-bottom: 0.25rem;
}

.detail-name p {
  font-size: 1rem;
  opacity: 0.9;
}

.detail-info-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: var(--spacing-lg);
}

.detail-info-card {
  display: flex;
  gap: var(--spacing-md);
  padding: var(--spacing-lg);
  background: var(--gray-50);
  border-radius: var(--radius-lg);
  border-left: 4px solid var(--primary-color);
  transition: all var(--transition-base);
}

.detail-info-card:hover {
  transform: translateX(4px);
  box-shadow: var(--shadow-md);
}

.detail-info-icon {
  font-size: 2rem;
  flex-shrink: 0;
}

.detail-info-content {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  flex: 1;
}

.detail-info-label {
  font-size: 0.75rem;
  font-weight: 600;
  color: var(--gray-500);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.detail-info-value {
  font-size: 1rem;
  font-weight: 600;
  color: var(--gray-900);
  text-transform: capitalize;
}

.detail-info-extra {
  font-size: 0.875rem;
  color: var(--gray-600);
}

@media (max-width: 768px) {
  .detail-modal {
    max-width: 100%;
  }
  
  .detail-info-grid {
    grid-template-columns: 1fr;
  }
  
  .detail-header {
    flex-direction: column;
    text-align: center;
  }
  
  .detail-avatar {
    width: 70px;
    height: 70px;
    font-size: 1.75rem;
  }
}
</style>
